//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppStoreEF
{
    using System.Data.Entity;
    using System.Windows;
    using System.Data.Entity.Infrastructure;
    using System.Windows.Controls;
    
    public partial class DBClientsEntities1 : DbContext
    {
        public DBClientsEntities1()
            : base("name=DBClientsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }

        public void LoadClients(DataGrid viewClients)
        {
            this.Clients.Load();
            viewClients.ItemsSource = this.Clients.Local.ToBindingList<Clients>();
        }

        //Добавить клиента
        public void AddClient()
        {
            Clients newClient = new Clients();
            ClientAddWindow add = new ClientAddWindow(newClient);
            add.ShowDialog();

            if (add.DialogResult.Value)
            {
                this.Clients.Add(newClient);
                this.SaveChanges();
            }
        }

        //Удалить клиента
        public void DeleteClient(Clients client)
        {
            this.Clients.Remove(client);
            this.SaveChanges();
        }

        //Редактировать клиента
        public void EditClient(Clients client)
        {
            ClientEditWindow add = new ClientEditWindow(client);
            add.ShowDialog();
            this.SaveChanges();
        }

        //Показать заказы клиента
        public void LoadClientOrders(Clients client)
        {
            if (client != null)
            {
                DesktopStoreOrders DesktopStoreOrdersWindow = new DesktopStoreOrders(client.Email.ToString());
                DesktopStoreOrdersWindow.ShowDialog();
            }
            else
            {
                MessageBox.Show("Выберите клиента, по которому нужно получить выборку заказов");
            }
        }
    }
}
