//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppStoreEF
{
    using System.Data.Entity;
    using System.Linq;
    using System.Data.Entity.Infrastructure;
    using System.Windows.Controls;

    public partial class DBOrdersEntities1 : DbContext
    {
        public DBOrdersEntities1()
            : base("name=DBOrdersEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Orders> Orders { get; set; }
        public void LoadOrders(string selectOrders, DataGrid viewOrders)
        {
            if (selectOrders == "full")
            {
                this.Orders.Load();
            }
            else
            {
                this.Orders.Where(order => order.Email == selectOrders).Load();
            }
            viewOrders.ItemsSource = this.Orders.Local.ToBindingList<Orders>();
        }

        //Добавить заказ
        public void AddOrder()
        {
            Orders newOrder = new Orders();
            OrderAddWindow add = new OrderAddWindow(newOrder);
            add.ShowDialog();

            if (add.DialogResult.Value)
            {
                this.Orders.Add(newOrder);
                this.SaveChanges();
            }
        }

        //Удалить заказ
        public void DeleteOrder(Orders order)
        {
            this.Orders.Remove(order);
            this.SaveChanges();
        }

        //Редактировать заказ
        public void EditOrder(Orders order)
        {
            OrderEditWindow add = new OrderEditWindow(order);
            add.ShowDialog();
            this.SaveChanges();
        }

    }
}
