//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillProfiDesktopApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class DBSkillProfiDesktopApplicationEntities : DbContext
    {
        public DBSkillProfiDesktopApplicationEntities()
            : base("name=DBSkillProfiDesktopApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }

        public string FindUser(string userName, string password)
        {
            Users user = Users.FirstOrDefault(u => u.UserName == userName);

            if (user != null)
            {
                if (user.Password.Trim() == password.ToString())
                {
                    return ($"Ок");
                }
                else
                {
                    return ("Неверный пароль");
                }
            }
            else
            {
                return ("Пользователь не найден");
            }
        }
    }
}
